os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -project LucidAnimationsSwift/LucidAnimationsSwift.xcodeproj -scheme LucidAnimationsSwiftTests -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.2,name=iPhone 8” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO